name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Linting
        run: npx eslint .

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Unit Tests
        run: npm test

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

  deployment:
    runs-on: ubuntu-latest
    needs: [ linting, unit_tests, build_and_test ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deployment
        run: ./deploy.sh