name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14' # Utilisez la version de Node.js que votre projet requiert

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build

  deployment:
    runs-on: ubuntu-latest
    needs: [ linting, unit_tests, build_and_test ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deployment
        run: ./deploy.sh